apiVersion: v1 
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    environment: dev
    project: sample-frontend
spec:
  replicas: 2
  selector: 
    matchLabels: 
      environment: dev
      project: sample-frontend
  template:
    metadata: 
      labels: 
        environment: dev
        project: sample-frontend
    spec: 
      containers: 
      - name: sample-frontend 
        image: 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"