apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: my-cluster-namespace
  labels:
    environment: dev
    project: sample-frontend
spec:
  replicas: 3
  selector: 
    matchLabels: 
      environment: dev
      project: sample-frontend
  template:
    metadata: 
      labels: 
        environment: dev
        project: sample-frontend
    spec: 
      containers: 
      - name: argo-frontend 
        image: sivaphanikumar/argo-frontend:v1 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "900Mi"
            cpu: "900m"

---
apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: my-cluster-namespace
  labels:
    environment: dev
    project: sample-frontend

spec:
  type: LoadBalancer

  selector:
    environment: dev
    project: sample-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80